#!/usr/bin/env bash
#
# Builds the Vivace Linux installer with Qt's CMake deployment API + Qt
# Installer Framework.
#
# There is NO linuxdeployqt in Qt 6 — deployment is done with `cmake --install`,
# which runs the deploy script generated by qt_generate_deploy_qml_app_script()
# in CMakeLists.txt. On Linux that uses CMake's own runtime-dependency scanning
# to gather the Qt libraries, QML modules and plugins into the standard
# bin/ + lib/ + plugins/ + qml/ layout with a bundled qt.conf.
#
# Prerequisites:
#   * Qt 6.11.x gcc_64 kit.
#   * Patchelf (used by the CMake deploy to fix rpaths).
#   * Qt Installer Framework (binarycreator) via the Qt Maintenance Tool.
#
# Env overrides: QT_DIR, IFW_DIR.
set -euo pipefail

QT_DIR="${QT_DIR:-$HOME/Qt/6.11.1/gcc_64}"
IFW_DIR="${IFW_DIR:-}"

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
build="$root/build-release"
pkg="$here/packages/org.vivaceplayer.vivace"
data="$pkg/data"

echo "== Configure + build (Release) =="
cmake -S "$root" -B "$build" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_DIR"
cmake --build "$build" -j"$(nproc)"

echo "== Deploy (cmake --install; no linuxdeployqt) =="
rm -rf "$data"
cmake --install "$build" --prefix "$data"
cp "$root/icons/app_256.png" "$data/vivace.png"      # placeholder until brand icon

echo "== License =="
cp "$root/LICENSE" "$pkg/meta/license.txt"

if [ -z "$IFW_DIR" ]; then
    IFW_DIR="$(ls -d "$HOME"/Qt/Tools/QtInstallerFramework/*/bin 2>/dev/null | sort -r | head -1 || true)"
fi
[ -n "$IFW_DIR" ] || { echo "Qt Installer Framework not found; set IFW_DIR." >&2; exit 1; }

echo "== binarycreator =="
out="$root/VivaceSetup-linux"
"$IFW_DIR/binarycreator" -c "$here/config/config.xml" -p "$here/packages" "$out"
echo "Installer: $out"
