#!/usr/bin/env bash
#
# Builds the Vivace macOS package with Qt's CMake deployment API.
#
# Deployment uses `cmake --install`, which runs the deploy script generated by
# qt_generate_deploy_qml_app_script() in CMakeLists.txt. For a macOS app bundle
# that drives macdeployqt under the hood, embedding the Qt frameworks, QML
# modules and plugins into vivace.app as private frameworks.
#
# Two distribution outputs (pick per your needs):
#   * A Qt Installer Framework installer (default here, for parity with
#     Windows/Linux) — set IFW_DIR or install IFW via the Qt Maintenance Tool.
#   * A .dmg disk image (the idiomatic macOS format) — pass --dmg, which runs
#     `macdeployqt vivace.app -dmg` instead of binarycreator.
#
# Signing/notarization (Apple Developer ID) is out of scope here; add
# `-codesign=<identity> -hardened-runtime -timestamp` to the macdeployqt call
# (or DEPLOY_TOOL_OPTIONS in CMakeLists) when you have a certificate.
#
# Env overrides: QT_DIR, IFW_DIR.  NOTE: untested — no macOS available here.
set -euo pipefail

MODE="ifw"
[ "${1:-}" = "--dmg" ] && MODE="dmg"

QT_DIR="${QT_DIR:-$HOME/Qt/6.11.1/macos}"
IFW_DIR="${IFW_DIR:-}"

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
build="$root/build-release"
pkg="$here/packages/org.vivaceplayer.vivace"
data="$pkg/data"

echo "== Configure + build (Release) =="
# -G Ninja, not the default "Unix Makefiles": a real CI failure
# (2026-08-18) showed `make` erroring "No rule to make target
# 'bluray-prefix/build/contrib/libudfread/src/libudfread.a', needed by
# 'vivace.app/...'" -- a BUILD_BYPRODUCTS file from the libbluray
# ExternalProject_Add step that CMake's Makefiles generator failed to
# wire a working rule for, even though the path itself is correct
# (verified against a real local build tree). This is the SAME class of
# "No rule to make target" failure already hit once before for
# libbluray.a itself on Linux (that one traced to a genuinely wrong
# path, Meson's Debian multiarch libdir default -- fixed with
# -Dlibdir=lib) -- but this new one has no such path explanation, since
# Meson's subproject build-tree layout doesn't vary by platform. Ninja
# is CMake's own reference generator for BUILD_BYPRODUCTS + ExternalProject
# (its docs specifically call out Ninja needing exact byproduct
# declarations to work at all, implying more rigorous handling than the
# Makefiles generator gets) and is already a required tool here anyway
# (libbluray's own Meson build uses --backend ninja), so this costs
# nothing new to install.
cmake -S "$root" -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_DIR"
cmake --build "$build" --parallel "$(sysctl -n hw.ncpu)"

echo "== Deploy (cmake --install -> macdeployqt) =="
rm -rf "$data"
cmake --install "$build" --prefix "$data"   # produces $data/vivace.app

if [ "$MODE" = "dmg" ]; then
    echo "== macdeployqt -dmg =="
    "$QT_DIR/bin/macdeployqt" "$data/vivace.app" -qmldir="$root/qml" -dmg
    mv "$data/vivace.dmg" "$root/Vivace-macos.dmg"
    echo "Disk image: $root/Vivace-macos.dmg"
    exit 0
fi

echo "== License =="
cp "$root/LICENSE" "$pkg/meta/license.txt"

if [ -z "$IFW_DIR" ]; then
    IFW_DIR="$(ls -d "$HOME"/Qt/Tools/QtInstallerFramework/*/bin 2>/dev/null | sort -r | head -1 || true)"
fi
[ -n "$IFW_DIR" ] || { echo "Qt Installer Framework not found; set IFW_DIR or use --dmg." >&2; exit 1; }

echo "== binarycreator =="
out="$root/VivaceSetup-macos"
"$IFW_DIR/binarycreator" -c "$here/config/config.xml" -p "$here/packages" "$out"
echo "Installer: $out"
